apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uvote-ingress
  namespace: uvote-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 5000
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 5001
      - path: /api/elections
        pathType: Prefix
        backend:
          service:
            name: election-service
            port:
              number: 5005
      - path: /api/voting
        pathType: Prefix
        backend:
          service:
            name: voting-service
            port:
              number: 5003
      - path: /api/results
        pathType: Prefix
        backend:
          service:
            name: results-service
            port:
              number: 5004
      - path: /api/admin
        pathType: Prefix
        backend:
          service:
            name: admin-service
            port:
              number: 5002
