apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: uvote-dev
type: Opaque
stringData:
  postgres-password: "dev_password_CHANGE_IN_PROD"
  database: "uvote"
  username: "uvote_admin"
